### ISSUE TITLE
ACRExtensions doesn't work on the latest read.amazon.com

### ISSUE THREAD

**Issue by jws325** [ccimpoi/ACRExtensions#14]
Hi,

The code for read.amazon.com was just updated.
ACRExtensions doesn't work anymore.

Thanks

**Comment by ccimpoi** [comment]
Yep. Looking into it but looks like they changed a lot.

**Comment by erata** [comment]
is there any quick fix?

**Comment by ccimpoi** [comment]
Yes I am working on a fix and I will have something early next week.

**Comment by ccimpoi** [comment]
Fixed it.
I gave up on overriding the UI and went straight for the XMLHttpRequest.prototype.send.
A bit more future proof but not as UX ish as before.
Still useful.

README updated with some notes.
