### ISSUE TITLE
Doesnt work at all on latest Kindle Cloud Reader

### ISSUE THREAD

**Issue by ccimpoi** [ccimpoi/ACRExtensions#15]
Fix asap.

**Comment by ccimpoi** [comment]
I checked the new reader and they totally moved everything server side. Client gets only images and highlight is done using only empty DIVs with server side provided coordinates.
Looks like the end of the road...
:-(

**Comment by marcmerlin** [comment]
thanks for your work.  Amazon sucks, no more kindle books for me.
